### PR TITLE
Upgrade to kube 1.2

### PR DESCRIPTION
**Pull request by huggsboson**
This was fairly disruptive.  I ended up removing docker-compose to
remove some variables and get it all working.

I'm just sending this to you as an FYI.  I did a bunch of things to try and get 1.2 working.

### CODE REVIEW

**Comment by vyshane** [comment]
I also started updating this project to use Kubernetes 1.2, and, like you, also ditched Docker Compose. I ended up with something [like this](https://github.com/vyshane/kid/blob/master/kid).

However, since I'm not using Docker Compose anymore, and because I broke backwards compatibility (different commands for up and down, removed kube-ui in favour of Kubernetes Dashboard), I've put this in a different repo. Would you be interested in collaborating in the new repo?

**Comment by huggsboson** [comment]
Super cool, I love the name and would love to collaborate.  I'll see how the new script works and potentially port any changes I need.

**Comment by huggsboson** [comment]
I'll try to get a PR up for kid in the next few days.  Main things I'd like to port over:
1. Use of kubectl context over port forwarding.
1a. Using manifests-multi: has api server listen on 0.0.0.0 instead of on 127.0.0.1, but requires running your own etcd, this makes kubectl context work instead of port forwarding.
2. Doing rm -Rf on /var/lib/kubelet.  I think you'll notice with the script you have now that multiple shut-downs and restarts will lead to skydns and other things that require api access tokens to work will start breaking.

**Comment by vyshane** [comment]
Thanks @huggsboson, that sounds good to me. I agree that using kubectl context is better than port forwarding.

> 1. Doing rm -Rf on /var/lib/kubelet. I think you'll notice with the script you have now that multiple shut-downs and restarts will lead to skydns and other things that require api access tokens to work will start breaking.

For my own future reference, upstream issue is kubernetes/kubernetes#23197.

**Pull request closed without merging**
