### PR TITLE
Add DaemonSet 

### PR DESCRIPTION
**Pull request by megastef**
Copy a manifest into kubernetes_master_1 container to  activate DaemonSets.
1. I've tried first  to mount the file /etc/kubernetes/manifests/master.json as volume, but a relative path is used in the apiserver setup "etc/kubernetes/manifests". And it is not possible to specify a relative path in volumes. 
2. I've tried to use /etc/, which did not work because the master container is mounting the host volume, and somehow the mount into /etc/ did not work. 
3. The final idea was then to use "docker cp" to copy the manifest after container creation. 
If you have a better idea to get the DaemonSets enabled pls. let me know.  There is no need to accept this PR. But I liked to share the problem - and I'm looking for a better way to activate DaemonSets :) 
TODO: add similar changes changes for multi-node manifest file.

### CODE REVIEW

**Comment by vyshane** [comment]
Is this still needed for Kubernetes 1.2, or do DaemonSets work out of the box there?

**Comment by megastef** [comment]
As far I have seen the DaemonSets are activated by default and use still extensions/v1beta1  (and not v1). So this could be closed, assuming you will upgrade to 1.2 sooner or later.

**Comment by vyshane** [comment]
I've started working on Kubernetes 1.2 support with @huggsboson [here](https://github.com/vyshane/kid). My current thinking is to keep the two repos separate because we're breaking backwards compatibility:
- We're getting rid of Docker Compose
- Everything will be in one script, which allows users to run `kid up`, `kid down` etc. from anywhere as long as the script is in their $PATH.
- We're also switching from port forwarding to using a kubectl context.

**Comment by huggsboson** [comment]
Deamonsets are enabled by default on 1.2, btw.

**Pull request closed without merging**
